name: Test and Deploy
on: [push]
jobs:
  run-checks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup venv
        run: make requirements

      - name: Run Security Checks
        run: make security-test

      - name: Run Flake
        run: make run-flake
      
      - name: Check Coverage
        run: make check-coverage

  run-tests:
    runs-on: ubuntu-latest
    needs: run-checks
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Setup venv
        run: make requirements

      - name: run-Test
        run: make unit-tests   
 
  deploy: 
    runs-on: ubuntu-latest
    needs: run-tests
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Setup AWS CLI Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with: 
          aws-region: eu-west-2
          aws-access-key-id: ${{ secrets.ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.SECRET_ACCESS_KEY }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        working-directory: Terraform
        run: terraform init
      
      - name: Terraform plan
        working-directory: Terraform
        run: terraform plan
 
      - name: Terraform apply
        working-directory: Terraform
        run: terraform apply -auto-approve 
        

